index:
    path: '/'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template:  'index.html.twig'

blog:
    path: '/blog'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template:  'chat.html.twig'
        context: { chat: 'blog' }

audio:
    path: '/audio'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template:  'chat.html.twig'
        context: { chat: 'audio' }

youtube:
    path: '/youtube'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template:  'chat.html.twig'
        context: { chat: 'youtube' }

wikipedia:
    path: '/wikipedia'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template:  'chat.html.twig'
        context: { chat: 'wikipedia' }
