ai:
    platform:
        openai:
            api_key: '%env(OPENAI_API_KEY)%'
    agent:
        blog:
            # platform: 'ai.platform.anthropic'
            model:
                class: 'Symfony\AI\Platform\Bridge\OpenAi\Gpt'
                name: !php/const Symfony\AI\Platform\Bridge\OpenAi\Gpt::GPT_4O_MINI
            tools:
                - 'Symfony\AI\Agent\Toolbox\Tool\SimilaritySearch'
                - service: 'clock'
                  name: 'clock'
                  description: 'Provides the current date and time.'
                  method: 'now'
        stream:
            model:
                class: 'Symfony\AI\Platform\Bridge\OpenAi\Gpt'
                name: !php/const Symfony\AI\Platform\Bridge\OpenAi\Gpt::GPT_4O_MINI
            system_prompt: |
                You are an example chat application where messages from the LLM are streamed to the user using
                Server-Sent Events via `symfony/ux-turbo` / Turbo Streams. This example does not use any custom
                javascript and solely relies on the built-in `live` & `turbo_stream` Stimulus controllers.
                Whatever the user asks, tell them about the application & used technologies.
            tools: false
        youtube:
            model:
                class: 'Symfony\AI\Platform\Bridge\OpenAi\Gpt'
                name: !php/const Symfony\AI\Platform\Bridge\OpenAi\Gpt::GPT_4O_MINI
            tools: false
        wikipedia:
            model:
                class: 'Symfony\AI\Platform\Bridge\OpenAi\Gpt'
                name: !php/const Symfony\AI\Platform\Bridge\OpenAi\Gpt::GPT_4O_MINI
                options:
                    temperature: 0.5
            system_prompt: 'Please answer the users question based on Wikipedia and provide a link to the article.'
            include_tools: true
            tools:
                - 'Symfony\AI\Agent\Toolbox\Tool\Wikipedia'
        audio:
            model:
                class: 'Symfony\AI\Platform\Bridge\OpenAi\Gpt'
                name: !php/const Symfony\AI\Platform\Bridge\OpenAi\Gpt::GPT_4O_MINI
            system_prompt: 'You are a friendly chatbot that likes to have a conversation with users and asks them some questions.'
            tools:
                # Agent in agent ðŸ¤¯
                - agent: 'blog'
                  name: 'symfony_blog'
                  description: 'Can answer questions based on the Symfony blog.'
    store:
        chroma_db:
            symfonycon:
                collection: 'symfony_blog'
    vectorizer:
        openai_embeddings:
            model:
                class: 'Symfony\AI\Platform\Bridge\OpenAi\Embeddings'
                name: !php/const Symfony\AI\Platform\Bridge\OpenAi\Embeddings::TEXT_ADA_002
    indexer:
        default:
            vectorizer: 'ai.vectorizer.openai_embeddings'
            store: 'ai.store.chroma_db.symfonycon'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Symfony\AI\Agent\Toolbox\Tool\Clock: ~
    # Symfony\AI\Agent\Toolbox\Tool\OpenMeteo: ~
    # Symfony\AI\Agent\Toolbox\Tool\SerpApi:
    #     $apiKey: '%env(SERP_API_KEY)%'
    Symfony\AI\Agent\Toolbox\Tool\Wikipedia: ~
    Symfony\AI\Agent\Toolbox\Tool\SimilaritySearch:
        $model: '@ai.indexer.default.model'
