name: RST Linter

on:
    push:
        paths:
            - '**.rst'
            - 'docs/**'
            - '.github/workflows/doctor-rst.yaml'
    pull_request:
        paths:
            - '**.rst'
            - 'docs/**'
            - '.github/workflows/doctor-rst.yaml'

jobs:
    doctor-rst:
        name: DOCtor-RST
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Create cache dir
              run: mkdir .cache

            - name: Extract base branch name
              run: echo "branch=$(echo ${GITHUB_BASE_REF:=${GITHUB_REF##*/}})" >> $GITHUB_OUTPUT
              id: extract_base_branch

            - name: Cache DOCtor-RST
              uses: actions/cache@v4
              with:
                  path: .cache
                  key: doctor-rst-${{ steps.extract_base_branch.outputs.branch }}

            - name: DOCtor-RST
              uses: docker://oskarstark/doctor-rst:1.70.2
              with:
                  args: --short --error-format=github --cache-file=/github/workspace/.cache/doctor-rst.cache
